SELECT 
  CONVERT(VARCHAR,PE.COD_BASE) AS IDBASE,
  CONVERT(VARCHAR,COD_EMBALAGEM) AS IDEMBTINTA,
  CONVERT(VARCHAR,PE.COD_PRODUTO) AS IDPRODUTO,
  B.DES_BASE AS DESCRICAO,
  '5' AS IDCOLECAO,
  'N' AS INATIVO
 FROM SELFCOLOR.dbo.V_TWEB_BASES PE
 INNER JOIN SELFCOLOR.dbo.V_TWEB_PRODUTOS P
    ON P.COD_PRODUTO = PE.COD_PRODUTO
  LEFT JOIN SELFCOLOR.dbo.V_TWEB_TIPOS_BASES B
    ON B.COD_BASE = PE.COD_BASE
 WHERE PE.SITUACAO = 'A' 
   AND P.SITUACAO = 'A';