SELECT 
  CONVERT(VARCHAR,COD_EMBALAGEM) AS IDEMBTINTA,
  DES_EMBALAGEM AS DESCRICAO,
  REPLACE(VOLUME,'.',',') AS CAPACIDADE,
  '5' AS IDCOLECAO
FROM SELFCOLOR.dbo.V_TWEB_EMBALAGENS E 
WHERE E.SITUACAO = 'A';