SELECT 
  CONVERT(VARCHAR, COD_COLORANTE) AS IDCORANTE,
  LTRIM(RTRIM(SIGLA_COLORANTE)) AS SIGLA,
  DES_COLORANTE AS DESCRICAO,
  '' AS COR,
  '5' AS IDCOLECAO,
  'N' AS INATIVO
FROM SELFCOLOR.dbo.V_TWEB_COLORANTES 
WHERE SITUACAO = 'A';