/*CORANTE*/
SELECT '"IDCORANTE"', '"SIGLA"', '"DESCRICAO"', '"COR"', '"IDCOLECAO"', '"INATIVO"'
UNION ALL
SELECT 
  CONVERT(VARCHAR, COD_COLORANTE) AS IDCORANTE,
  LTRIM(RTRIM(SIGLA_COLORANTE)) AS SIGLA,
  DES_COLORANTE AS DESCRICAO,
  '' AS COR,
  '5' AS IDCOLECAO,
  'N' AS INATIVO
FROM SELFCOLOR.dbo.V_TWEB_COLORANTES 
WHERE SITUACAO = 'A';

/*GRUPOTINTA*/
SELECT '"IDCOLECAO"','"IDGRUPOTINTA"','"DESCRICAO"','"SITUACAO"'
UNION ALL
SELECT 
  '5' AS IDCOLECAO,
  CONVERT(VARCHAR,COD_GRUPO) AS IDGRUPOTINTA,	
  SUBSTRING(DES_GRUPO,1,60) AS DESCRICAO,
  SITUACAO
FROM SELFCOLOR.dbo.V_TWEB_GRUPOS 
WHERE SITUACAO = 'A';

/*PRODUTO*/
SELECT '"IDPRODUTO"','"DESCRICAO"','"IMAGEM"', '"IDCOLECAO"','"INATIVO"'
UNION ALL
SELECT 
  CONVERT(VARCHAR,COD_PRODUTO) AS IDPRODUTO,
  DES_PRODUTO AS DESCRICAO,
  '' AS IMAGEM,
  '5' AS IDCOLECAO,
  'N' AS INATIVO
FROM SELFCOLOR.dbo.V_TWEB_PRODUTOS 
WHERE SITUACAO = 'A';

/*EMBTINTA*/
SELECT '"IDEMBTINTA"', '"DESCRICAO"','"CAPACIDADE"','"IDCOLECAO"'
UNION ALL
SELECT 
  CONVERT(VARCHAR,COD_EMBALAGEM) AS IDEMBTINTA,
  DES_EMBALAGEM AS DESCRICAO,
  REPLACE(VOLUME,'.',',') AS CAPACIDADE,
  '5' AS IDCOLECAO
FROM SELFCOLOR.dbo.V_TWEB_EMBALAGENS E 
WHERE E.SITUACAO = 'A';

/*BASE*/
SELECT '"IDBASE"', '"IDEMBTINTA"', '"IDPRODUTO"', '"DESCRICAO"', '"IDCOLECAO"', '"INATIVO"'
UNION ALL
SELECT 
  CONVERT(VARCHAR,PE.COD_BASE) AS IDBASE,
  CONVERT(VARCHAR,COD_EMBALAGEM) AS IDEMBTINTA,
  CONVERT(VARCHAR,PE.COD_PRODUTO) AS IDPRODUTO,
  B.DES_BASE AS DESCRICAO,
  '5' AS IDCOLECAO,
  'N' AS INATIVO
 FROM SELFCOLOR.dbo.V_TWEB_BASES PE
 INNER JOIN SELFCOLOR.dbo.V_TWEB_PRODUTOS P
    ON P.COD_PRODUTO = PE.COD_PRODUTO
  LEFT JOIN SELFCOLOR.dbo.V_TWEB_TIPOS_BASES B
    ON B.COD_BASE = PE.COD_BASE
 WHERE PE.SITUACAO = 'A' 
   AND P.SITUACAO = 'A';

/*MSGTINTA*/
SELECT '"IDMSGTINTA"', '"DESCRICAO"','"IDCOLECAO"'
UNION ALL
SELECT 
  CONVERT(VARCHAR,COD_MENSAGEM) AS IDMSGTINTA,
  '"'+MENSAGEM+'"' AS DESCRICAO,
  '5' AS IDCOLECAO
FROM SELFCOLOR.dbo.TMENSAGENS

/*FORMULA*/
SELECT '"IDFORMULA"', '"IDCOLECAO"', '"IDBASE"', '"IDPRODUTO"', '"IDMSGTINTA"', '"DESCRICAO"', '"CODCATALOGO"', '"IDEMBTINTA"', '"IDGRUPOTINTA"', '"INATIVO"', '"PERSONALIZADA"'
UNION ALL
SELECT 
   CONVERT(VARCHAR,C.ID) AS IDFORMULA,
   '5' AS IDCOLECAO,
   CONVERT(VARCHAR,C.COD_BASE) AS IDBASE,
   CONVERT(VARCHAR,C.COD_PRODUTO) AS IDPRODUTO,
   COALESCE((SELECT CAST(T.COD_MENSAGEM AS VARCHAR)
   FROM SELFCOLOR.dbo.TMENSAGENS_FORMULAS T 
   JOIN SELFCOLOR.dbo.TMENSAGENS T2 ON T2.COD_MENSAGEM = T.COD_MENSAGEM
   WHERE T.COD_BASE = C.COD_BASE
   AND T.COD_COR = C.COD_COR
   AND T.COD_EMBALAGEM = C.COD_EMBALAGEM
   AND T.COD_GRUPO = C.COD_GRUPO
   AND T.COD_PRODUTO = C.COD_PRODUTO
   AND T.SITUACAO = 'A'),'') AS IDMSGTINTA,
   C.NOM_COR AS DESCRICAO,
   C.DES_COR AS CODCATALOGO,
   CONVERT(VARCHAR,C.COD_EMBALAGEM) AS IDEMBTINTA,
   CONVERT(VARCHAR,C.COD_GRUPO) AS IDGRUPOTINTA,
   'N' AS INATIVO,
   'N' AS PERSONALIZADA
 FROM SELFCOLOR.dbo.V_TWEB_CORES C
 INNER JOIN SELFCOLOR.dbo.V_TWEB_GRUPOS G ON C.COD_GRUPO = G.COD_GRUPO
 INNER JOIN SELFCOLOR.dbo.V_TWEB_PRODUTOS P ON C.COD_PRODUTO = P.COD_PRODUTO
 INNER JOIN SELFCOLOR.dbo.V_TWEB_TIPOS_BASES TB ON C.COD_BASE = TB.COD_BASE
 INNER JOIN SELFCOLOR.dbo.V_TWEB_EMBALAGENS E ON C.COD_EMBALAGEM = E.COD_EMBALAGEM
 WHERE C.SITUACAO = 'A'
 AND G.SITUACAO = 'A';

/*FORMULACORANTE*/
SELECT '"IDFORMULA"', '"IDCORANTE"', '"SEQCORANTE"', '"QTDEOZ1"', '"QTDEOZ2"', '"QTDEML"', '"QTDEGR"', '"IDCOLECAO"'
UNION ALL
SELECT 
   CONVERT(VARCHAR,F.ID) AS IDFORMULA,
   CONVERT(VARCHAR,C.COD_COLORANTE) AS IDCORANTE,
   CONVERT(VARCHAR,ROW_NUMBER() OVER (PARTITION BY F.ID ORDER BY F.ID)) AS SEQCORANTE,
   '' AS QTDEOZ1,
   '' AS QTDEOZ2,
   REPLACE(C.QTDE * 0.154,'.',',') AS QTDEML,
   '' AS QTDEGR,
   '5' AS IDCOLECAO
 FROM SELFCOLOR.dbo.V_TWEB_CORES F
 INNER JOIN SELFCOLOR.dbo.V_TWEB_CORES_COLORANTES C
    ON F.COD_GRUPO     = C.COD_GRUPO
   AND F.COD_PRODUTO   = C.COD_PRODUTO
   AND F.COD_BASE      = C.COD_BASE
   AND F.COD_EMBALAGEM = C.COD_EMBALAGEM
   AND F.COD_COR       = C.COD_COR
 INNER JOIN SELFCOLOR.dbo.V_TWEB_GRUPOS G ON C.COD_GRUPO = G.COD_GRUPO 
 INNER JOIN SELFCOLOR.dbo.V_TWEB_COLORANTES R ON C.COD_BASE = R.COD_COLORANTE
 INNER JOIN SELFCOLOR.dbo.V_TWEB_PRODUTOS P ON C.COD_PRODUTO = P.COD_PRODUTO
 INNER JOIN SELFCOLOR.dbo.V_TWEB_TIPOS_BASES TB ON C.COD_BASE = TB.COD_BASE
 INNER JOIN SELFCOLOR.dbo.V_TWEB_EMBALAGENS E ON C.COD_EMBALAGEM = E.COD_EMBALAGEM
 WHERE C.QTDE > 0
 AND F.SITUACAO = 'A'
 AND G.SITUACAO = 'A';